# Generated by Django 2.0.4 on 2018-04-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('travel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('payment_id', models.IntegerField()),
                ('travel_date', models.DateField()),
            ],
        ),
    ]
