# Generated by Django 2.0.4 on 2018-04-29 17:44

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('line1', models.CharField(max_length=50)),
                ('line2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('amenities_id', models.IntegerField(primary_key=True, serialize=False)),
                ('breakfast', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('fitness', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('bar', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('number', models.CharField(default=0, max_length=5)),
                ('cost', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('car_confirmation_id', models.IntegerField()),
                ('car_class', models.CharField(choices=[('COMMERCIAL', 'commercial'), ('CONVERTIBLE', 'convertible'), ('VAN', 'van'), ('TRUCK', 'truck'), ('LUXURY', 'luxury'), ('SUV', 'suv')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('number', models.CharField(default=0, max_length=5)),
                ('cost', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
                ('cruise_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.ForeignKey(default=1, on_delete='DO_NOTHING', to='travel_agency.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('number', models.CharField(default=0, max_length=5)),
                ('cost', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
                ('flight_id', models.IntegerField(primary_key=True, serialize=False)),
                ('flight_class', models.CharField(choices=[('ECONOMY', 'economy'), ('BUSINESS', 'business'), ('FIRST', 'first')], max_length=10)),
                ('company', models.ForeignKey(default=1, on_delete='DO_NOTHING', to='travel_agency.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('number', models.CharField(default=0, max_length=5)),
                ('available', models.IntegerField(default=0)),
                ('hotel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cost', models.IntegerField()),
                ('addr', models.OneToOneField(on_delete='CASCADE', to='travel_agency.Address')),
                ('amenities', models.OneToOneField(on_delete='CASCADE', to='travel_agency.Amenities')),
                ('company', models.ForeignKey(default=1, on_delete='DO_NOTHING', to='travel_agency.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=2, null=True)),
                ('country', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('credit_no', models.IntegerField()),
                ('expiry', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=254)),
                ('billing_addr', models.OneToOneField(blank=True, null=True, on_delete='CASCADE', related_name='profile_billing_addr', to='travel_agency.Address')),
                ('home_addr', models.OneToOneField(blank=True, null=True, on_delete='CASCADE', related_name='profile_home_addr', to='travel_agency.Address')),
                ('payment_method', models.ForeignKey(null=True, on_delete='DO_NOTHING', to='travel_agency.Payment')),
                ('user_id', models.OneToOneField(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=256)),
                ('rating', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('company_id', models.ForeignKey(on_delete='DO_NOTHING', to='travel_agency.Company')),
                ('user_id', models.ForeignKey(on_delete='DO_NOTHING', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('search_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('from_date', models.DateField(default=datetime.datetime.now)),
                ('to_date', models.DateField(default=datetime.datetime.now, null=True)),
                ('travelers_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('from_location', models.ForeignKey(on_delete='DO_NOTHING', related_name='search_from_location', to='travel_agency.Location')),
                ('to_location', models.ForeignKey(null=True, on_delete='DO_NOTHING', related_name='search_to_location', to='travel_agency.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('travel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('payment_id', models.IntegerField()),
                ('travel_date', models.DateField(default=datetime.datetime.now)),
                ('from_location', models.ForeignKey(on_delete='DO_NOTHING', related_name='travel_from_location', to='travel_agency.Location')),
                ('to_location', models.ForeignKey(on_delete='DO_NOTHING', related_name='travel_to_location', to='travel_agency.Location')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.OneToOneField(on_delete='DO_NOTHING', to='travel_agency.Location'),
        ),
        migrations.AddField(
            model_name='flight',
            name='location',
            field=models.ForeignKey(default=1, on_delete='DO_NOTHING', to='travel_agency.Location'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='location',
            field=models.ForeignKey(default=1, on_delete='DO_NOTHING', to='travel_agency.Location'),
        ),
        migrations.AddField(
            model_name='car',
            name='company',
            field=models.ForeignKey(default=1, on_delete='DO_NOTHING', to='travel_agency.Company'),
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.ForeignKey(default=1, on_delete='DO_NOTHING', to='travel_agency.Location'),
        ),
    ]
