# Generated by Django 2.0.4 on 2018-04-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='location',
        ),
        migrations.AddField(
            model_name='flight',
            name='from_location',
            field=models.ForeignKey(default=1, on_delete='DO_NOTHING', related_name='flight_from_location', to='travel_agency.Location'),
        ),
        migrations.AddField(
            model_name='flight',
            name='to_location',
            field=models.ForeignKey(default=1, on_delete='DO_NOTHING', related_name='flight_to_location', to='travel_agency.Location'),
        ),
    ]
