# Generated by Django 2.0.4 on 2018-04-29 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency', '0002_auto_20180429_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='car',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='cruise',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='cruise',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='flight',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='flight',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='hotel',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='hotel',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
