# Generated by Django 2.0.4 on 2018-04-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency', '0003_auto_20180429_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_confirmation_id',
            new_name='confirmation_id',
        ),
        migrations.RemoveField(
            model_name='car',
            name='location',
        ),
        migrations.RemoveField(
            model_name='cruise',
            name='location',
        ),
        migrations.AddField(
            model_name='car',
            name='from_location',
            field=models.ForeignKey(default=1, on_delete='DO_NOTHING', related_name='car_from_location', to='travel_agency.Location'),
        ),
        migrations.AddField(
            model_name='car',
            name='to_location',
            field=models.ForeignKey(default=1, on_delete='DO_NOTHING', related_name='car_to_location', to='travel_agency.Location'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='from_location',
            field=models.ForeignKey(default=1, on_delete='DO_NOTHING', related_name='cruise_from_location', to='travel_agency.Location'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='to_location',
            field=models.ForeignKey(default=1, on_delete='DO_NOTHING', related_name='cruise_to_location', to='travel_agency.Location'),
        ),
    ]
