# Generated by Django 2.0.4 on 2018-04-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency', '0004_auto_20180429_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
