# Generated by Django 2.0.3 on 2018-04-30 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency', '0006_auto_20180430_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='internet',
        ),
    ]
